language: ruby
before_install:
  - gem install bundler
script:
  - bundle exec jekyll build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master